### ISSUE TITLE
How to solve the following errors when compile with vs2015?

### ISSUE THREAD

**Issue by lozpeng** [chenguanzhou/QGIS-Windows-Build-Qt5-VS2015-x64#3]
1>  qgsgpsconnection.cpp
1>C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\cstdint(18): error C2039: “int8_t”: 不是“`global namespace'”的成员
1>C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\cstdint(18): error C2873: “int8_t”: 符号不能用在 using 声明中
1>C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\cstdint(18): error C2039: “int16_t”: 不是“`global namespace'”的成员
1>C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\cstdint(18): error C2873: “int16_t”: 符号不能用在 using 声明中
1>C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\cstdint(19): error C2039: “int32_t”: 不是“`global namespace'”的成员
1>C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\cstdint(19): error C2873: “int32_t”: 符号不能用在 using 声明中
1>C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\cstdint(19): error C2039: “int64_t”: 不是“`global namespace'”的成员
1>C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\cstdint(19): error C2873: “int64_t”: 符号不能用在 using 声明中

**Comment by chenguanzhou** [comment]
Did you built it in x86 (32 bit) mode?

**Comment by lozpeng** [comment]
no in x64 mode

**Comment by chenguanzhou** [comment]
This project (QGIS-Windows-Build-Qt5-VS2015-x64 ) is only for x64 mode.

**Comment by lozpeng** [comment]
yes,I am also build qgis in Qt5.7.1 +VS2015 X64 mode
